---
title: "Research"
---

Please find my research statement [here](https://drive.google.com/file/d/1R9OyidiRlrKcP1TUoETsDvF2MeFB0xCy/view?usp=share_link).

## Working Papers

### Employment Effects of Minimum Wages in Dual Economy: Evidence from Thailand

Job market paper; Revisions requested from *Journal of Development Economics* [Latest draft](https://drive.google.com/file/d/16RGwQSYVNAKzSWGohDojoHJSc42aX1Eq/view?usp=share_link)

This study estimates the impact of a minimum wage increase on employment when minimum wage coverage is incomplete. Using as a natural experiment a 60 percent increase in the minimum wage in Thailand whereby 40 percent of workers were not covered by the legislation, we found that one percent increase in the minimum wage reduced low-skilled employment in the covered sector by 0.4 percent and increased employment in the uncovered sector by 0.2 percent. The official unemployment rate also decreased because the rise in the minimum wage lowered the probability of covered employment to such a large extent that workers instead turned to the uncovered sector. Although the average wage in the covered sector increased, it is unclear whether the increased labor supply in the uncovered sector suppressed wages because 70 percent of the wages in the uncovered sector were not observed. 

### Formal-Informal Labor Allocative Efficiency of Minimum Wages: A Tale from Small Farm Enterprises

This paper studies the production in the informal sector after the minimum wage increase in the formal sector. According to the simplistic two-sector model by Welch (1974), an increase in minimum wage creates an outflow of labor from the formal to the informal sector, but little is known about what happens to production activities in the informal sector afterward. In the spirit of Lewis (1954), because there is surplus labor in the informal sector, production should not increase. However, many empirical studies have disputed the presence of surplus labor. Using a novel minimum wage policy from Thailand, we found the minimum wage increase induced workers to move to the informal sector, and there was an increase in production, contradicting the surplus labor hypothesis. We also found that despite the increase in the number of workers, the marginal product of labor in the informal sector increased. This suggests that newly hired workers brought some specialization that enhanced production substantially. As indirect evidence, we found they were more educated and younger than the existing ones.

### Husband's Death and Widow's Labor Supply Decision: Evidence from Rural Thai Households 

This study investigates the impact of the death of the primary earner of the household on the labor supply decision of the remaining household member, using a novel household panel data set from the Townsend Thai Data Collection. This data allows for the study of households in rural areas, in contrast to literature which often focus on more developed societies with a complete insurance coverage. We employed an Imputation Difference-in-differences estimator by \cite{borusyak2021revisiting} and found death of a husband increased labor supply decision of widows by 60 percent. On the other hand, there was little effect on widowers in the event of wife's death. The results suggested the death insurance coverage was not sufficient for Thai elderly households to overcome a permanent income loss.

## Research Grant

- Bank of Thailand's [Puey Ungphakorn Institute for Economic Research](https://www.pier.or.th/en/about/#top) Grant 2022 for the Project *Husband's Death and Widows' Labor Supply Decision: Evidence from Thai Household Panel*

## Presentations

- Husband's Death and Widows' Labor Supply Decision: Evidence from Rural Thai Households; [Asian and Australasian Society of Labour Economics 2022 Conference](https://www.aasle.org/); December, 2022; University of Tokyo

- Husband's Death and Widows' Labor Supply Decision: Evidence from Rural Thai Households; The 25th Tokyo Labor Economics Conference (第25回労働経済学カンファレンス); September, 2022; Online meeting

- Employment Effects of Minimum Wages in Dual Economy: Evidence from Thailand. [Asian and Australasian Society of Labour Economics 2021 Conference](https://www.aasle.org/); December, 2021; Peking University, Online Event

- Impact of Minimum Wages on Employment in Dual Economy: Evidence from Thailand. Poster presented at [SSSI Summer School on Socioeconomic Inequality](https://hceconomics.uchicago.edu/sssi.uchicago.edu); August, 2021; Online meeting

- Impact of Minimum Wages on Employment in Dual Economy: Evidence from Thailand. [The 15th Applied Econometrics Conference](http://www.crepe.e.u-tokyo.ac.jp/index.html)(第15回応用計量経済学コンファレンス); November, 2020; Online meeting

- Effect of Minimum Wages on Formal and Informal Employment
in Japan & Thailand. UTokyo Center of Contemporary Japanese Studies, TCJS Graduate Student Forum; November, 2020; Online meeting

- Impact of Minimum Wages on Employment in Dual Economy: Evidence from Thailand. Poster presented at: [The 23rd Tokyo Labor Economics Conference](https://sites.google.com/site/tokyolaborwkshp/home) (第23回労働経済学カンファレンス); October, 2020; Online meeting

